[package]
name = "snailcrypt-cli"
version = "0.2.0"
edition = "2021"
license = "proprietary"

[dependencies]
getopts = "0.2"
chrono = "0.4.23"
url = "2.3.1"
snailcrypt = "0.1.0"

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.4"
