[package]
name = "snailcrypt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2"
chrono = "0.4.23"
snailcrypt = { path = "/Users/ritsch_master/Documents/Work/snailcrypt/snailcrypt", version = "0.1.0" }

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.4"
